name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: keggcharter:latest
          outputs: type=docker,dest=/tmp/keggcharter.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: keggcharter
          path: /tmp/keggcharter.tar

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: keggcharter
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/keggcharter.tar
          docker image ls -a

      - name: Check base entrypoint
        run: docker run keggcharter /bin/bash -c "ls"

      - name: Run KEGGCharter
        run: docker run keggcharter /bin/bash -c "keggcharter.py -f KEGGCharter/ci/keggcharter_input.tsv -rd resources_directory -mm 00190,00680 -keggc 'Cross-reference (KEGG)'"
